import { type NextPage } from "next";
import Head from "next/head";
import { AuthShowcase } from "../components/AuthShowCase";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.event.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Football Organizer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Football <span className="text-purple-300">Organizer</span> App
        </h1>
        <div className="mt-3 grid gap-3 pt-3 text-center md:grid-cols-3 lg:w-2/3"></div>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;
