import { type NextPage } from "next";
import Head from "next/head";
import { AuthShowcase } from "../components/AuthShowCase";
import { OrganizerMap } from "../components/Map";

const Home: NextPage = () => {
  return (
    <div>
      <div
        style={{
          background: "linear-gradient(to top, #373B44, #73C8A9)",
        }}
        className="fixed -z-10 flex h-full w-full"
      />
      <Head>
        <title>Football Organizer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Football <span className="text-purple-300">Organizer</span> App
        </h1>
        <AuthShowcase />

        <div className="relative h-[500p] w-[500px]">
          <OrganizerMap />
        </div>
      </main>
    </div>
  );
};

export default Home;
