name: Cronjob for bookingReminder

on:
  schedule:
    - cron: '*/20 8-20 * * 1-5'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          SENDINBLUE_API_KEY: ${{secrets.SENDINBLUE_API_KEY}}
        run: bun test
