name: Cronjob for bookingReminder

on:
  schedule:
    - cron: '*/20 8-20 * * 1-5'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Install dependencies
        run: yarn install

      - name: Run
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          SENDINBLUE_API_KEY: ${{secrets.SENDINBLUE_API_KEY}}
        run: yarn test
