name: Cronjob

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        env:
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          GMAIL_REDIRECT_URIS: ${{secrets.GMAIL_REDIRECT_URIS}}
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}

      - name: Run cronjob
        run: bun cronjob
