name: Cronjob for Padel reminder

on:
  schedule:
    - cron: '*/5 7-10 * * 1'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Install dependencies
        run: bun install

      - name: Run
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          SENDINBLUE_API_KEY: ${{secrets.SENDINBLUE_API_KEY}}
        run: yarn test padelScript
