name: Cronjob for payments

on:
  schedule:
    - cron: '1 */6 * * *'

jobs:
  cronjob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        env:
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          GMAIL_REDIRECT_URIS: ${{secrets.GMAIL_REDIRECT_URIS}}
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          INNGEST_EVENT_KEY: ${{secrets.INNGEST_EVENT_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}

      - name: Install dependencies
        run: yarn install
        env:
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          GMAIL_REDIRECT_URIS: ${{secrets.GMAIL_REDIRECT_URIS}}
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          INNGEST_EVENT_KEY: ${{secrets.INNGEST_EVENT_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}

      - name: Run cronjob
        run: yarn cronjob
        env:
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          GMAIL_REDIRECT_URIS: ${{secrets.GMAIL_REDIRECT_URIS}}
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          INNGEST_EVENT_KEY: ${{secrets.INNGEST_EVENT_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
