name: Cronjob for payments

on:
  schedule:
    - cron: '1 */6 * * *'

jobs:
  cronjob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: bun install

      - name: Run cronjob
        run: bun cronjob
        env:
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          GMAIL_REDIRECT_URIS: ${{secrets.GMAIL_REDIRECT_URIS}}
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          INNGEST_EVENT_KEY: ${{secrets.INNGEST_EVENT_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          NODE_ENV: 'production'
          NEXTAUTH_SECRET: ''
          NEXTAUTH_URL: 'http://localhost:3000'
